#%RAML 1.0 Library
usage: Library of DataTypes

types:
  Partner: !include ../datatypes/partner.raml
  Flight: !include ../datatypes/flight.raml
  Booking: !include ../datatypes/booking.raml
  Error: !include ../datatypes/Error.raml
  Status: !include ../datatypes/Status.raml