#%RAML 1.0 NamedExample
value:
  flightId: 1
  code: Ind_Del
  price: 400.00
  departureDate: 2022-07-26
  origin: MAD
  destination: DEL
  emptySeats: 150
  plane: 
    planeType: Economic
    totalSeats: 150