#%RAML 1.0 NamedExample
value:
  flightId: 2
  code: Ind_Blr
  price: 540.00
  departureDate: 2022-07-26
  origin: HYD
  destination: BLR
  emptySeats: 90
  plane: 
    planeType: Economic
    totalSeats: 90